config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :contacts do
    resources :messages
  end

  root to: "contacts#index", only: [:index]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  acts_as_paranoid

  belongs_to :user, foreign_key: :contacter
end

app/models/message.rb
class Message < ApplicationRecord
  acts_as_paranoid

  belongs_to :sender, class_name: :User, foreign_key: "sender_id"
  belongs_to :receiver, class_name: :User, foreign_key: "receiver_id"

  scope :unred, -> { where(status: "unread") }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts, foreign_key: "owner"

  has_many :sent_messages, foreign_key: "sender_id", class_name: :Message
  has_many :received_messages, foreign_key: "receiver_id", class_name: :Message

  def messages(contact_id)
    Message.where("sender_id = ? AND receiver_id = ? OR sender_id = ? AND receiver_id = ?", self.id, contact_id, contact_id, self.id)
  end

  def unread_messages
    received_messages.where(status: "unread").count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @users = User.all
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.new(contact_params)
    user = User.find_by(id: contact_params[:contacter])
    isSelf = @contact.contacter == current_user.id

    respond_to do |format|
      if !isSelf && user && @contact.save
        format.html { redirect_to contacts_url, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { redirect_to :new_contact, notice: 'Contact was not existed.' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:contacter)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @contact = Contact.find_by(id: params[:contact_id])
    @messages = current_user.messages(@contact.contacter).order("created_at")
    current_user.received_messages.update_all(status: 'readed')
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    p params[:content]
    @contact = Contact.find_by(id: params[:contact_id])
    @message = Message.new(sender_id: current_user.id, receiver_id: @contact.contacter, content: params[:content])

    respond_to do |format|
      if @message.save
        format.html { redirect_to contact_messages_url, notice: 'Message was successfully created.' }
      else
        format.html { render :index }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to contact_messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/application/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>流利说</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>流利说</b>Messages</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/application/_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">流利说Messages</li>
      <% current_user.contacts.each_with_index do |c,index| %>
        <li class="treeview">
          <a href="<%= contact_messages_path(c.id)%>">
            <i class="fa fa-user"></i>
            <span><%= c&.user&.email %></span>
            <% if (unread = current_user.unread_messages) > 0%>
              <span class="pull-right-container">
                <span class="label bg-green pull-right">
                  <%= unread %>
                </span>
              </span>
            <%end%>
          </a>
        </li>
      <% end %>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/contacts/_form.html.erb
<%= simple_form_for @contact, as: :contact, html: { class: 'form-horizontal' }, 
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  <%= f.error_notification %>

  <%= f.input :contacter, label: 'user id'%>

  <div class="box-footer">
    <%= f.button :submit, class:"btn btn-info" %>
    <%= link_to '返回', contacts_path, class: "btn btn-default pull-right" %>
  </div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<section class="content-header">
  <h1>Contacts<small>list all contacts</small></h1>

  <button 
    type="button" 
    class="btn btn-block btn-info btn-lg" 
    style="width: 200px;float: right;margin-bottom: 15px;" 
    onclick="location.href='<%= new_contact_path %>'">Add Contact
  </button>

</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">all contacts</h3>
        </div>
        <div class="box-body">
          <div id="contact_list" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row"><div class="col-sm-12">
                <table class="table table-striped dataTable" role="grid">
                  <thead>
                    <tr role="row">
                      <th>id</th>
                      <th>email</th>
                      <th>unread</th>
                      <th style="max-width: 50px;">operations</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @contacts.each_with_index do |c,index| %>
                      <tr role="row" class="<%= index.odd? ? "odd" : "even" %>">
                        <td><%= c&.contacter %></td>
                        <td><%= c&.user&.email %></td>
                        <td><%= current_user.unread_messages %></td>
                        <td style="width: 200px;">
                          <%= link_to '消息', contact_messages_path(c.id), class:"btn btn-primary" %> 
                          <%= link_to '删除', contact_path(c.id), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }%> 
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
            </div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<section class="content-header">
  <h1>添加<small>联系人</small></h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Add Contacts</h3>
        </div>
        <div class="box-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">all User</h3>
        </div>
        <div class="box-body">
          <div class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row"><div class="col-sm-12">
                <table class="table table-striped dataTable" role="grid">
                  <thead>
                    <tr role="row">
                      <th>id</th>
                      <th>email</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @users.each_with_index do |u,index| %>
                      <tr role="row" class="<%= index.odd? ? "odd" : "even" %>">
                        <td><%= u.id %></td>
                        <td><%= u.email %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
            </div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Liulishuo</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
     <%= content_for?(:body) ? yield(:body) : raw('<body class="hold-transition skin-blue sidebar-mini">') %>
    <div class="wrapper">
      <%= render "header" %>
      <%= render "sidebar" %>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <%= yield %>
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0.0
        </div>
        <strong>Author: Edison-Hsu</strong>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>JuhuiwanAdmin</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <%= content_for?(:body) ? yield(:body) : raw('<body class="hold-transition skin-blue sidebar-mini">') %>
    <div class="wrapper">
      <%= yield %>
      <!-- /.content-wrapper -->
      <%# <footer class="devise-footer" style="margin-left:400px; margin-right:400px"> %>
      <%#   <div class="pull-right hidden-xs"> %>
      <%#     <b>Version</b> 1.0.0 %>
      <%#   </div> %>
      <%#   <strong>Copyright &copy; 2014-2016 <a href="http://juhuiwan.cn">聚会玩</a>.</strong> All rights %>
      <%#   reserved. %>
      <%# </footer> %>

    </div>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<section class="content-header">
  <h1>Messages<small>list all messages</small></h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-warning direct-chat direct-chat-warning">
        <div class="box-header with-border">
          <h3 class="box-title">Message Chat</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body" style="min-height: 500px">
          <!-- Conversations are loaded here -->
          <div id="chat-messages" class="direct-chat-messages" style="min-height: 500px">
            <% @messages.each do |m| %>
              <% if m.sender.id == current_user.id %>
                <div class="direct-chat-msg right">
                  <div class="direct-chat-info clearfix">
                    <span class="direct-chat-name pull-left"><%= current_user.email %></span>
                    <span class="direct-chat-timestamp pull-right"><%= m.created_at %></span>
                  </div>
                  <!-- /.direct-chat-info -->
                  <img class="direct-chat-img" src="/user1-128x128.jpg" alt="message user image"><!-- /.direct-chat-img -->
                  <div class="direct-chat-text">
                    <%= m.content %>
                          <%= link_to '删除', contact_message_path(params[:contact_id], m.id), method: :delete, data: { confirm: 'Are you sure?' }%> 
                    
                  </div>
                  <!-- /.direct-chat-text -->
                </div>
              <%else%>
                <!-- Message. Default to the left -->
                <div class="direct-chat-msg">
                  <div class="direct-chat-info clearfix">
                    <span class="direct-chat-name pull-left"><%= m.sender.email %></span>
                    <span class="direct-chat-timestamp pull-right"><%= m.created_at %></span>
                  </div>
                  <!-- /.direct-chat-info -->
                  <img class="direct-chat-img" src="/user3-128x128.jpg" alt="message user image"><!-- /.direct-chat-img -->
                  <div class="direct-chat-text">
                    <%= m.content %>
                  </div>
                  <!-- /.direct-chat-text -->
                </div>
                <!-- /.direct-chat-msg -->

              <% end%>
            <% end %>
          </div>
          <!-- /.direct-chat-pane -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <form action=<%= contact_messages_path %> method="post">
            <div class="input-group">
              <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
              <input type="text" name="content" placeholder="Type Message ..." class="form-control">
              <span class="input-group-btn">
                <button type="submit" class="btn btn-warning btn-flat">Send</button>
              </span>
            </div>
          </form>
        </div>
        <!-- /.box-footer-->
      </div>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>